apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: windows-enterprise-lab
  namespace: argocd
spec:
  destination:
    namespace: apps
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/NagadeepReddy/k8s-windows-enterprise-lab.git
    path: helm/enterprise-app
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
